### ISSUE TITLE
phpenv shell doesn't work

### ISSUE THREAD

**Issue by heitorsilva** [madumlao/phpenv#11]
Hi!

I'm testing phpenv with a Debian 8.5, and when I do `phpenv shell 7.0.8` or `phpenv shell --unset`, it gives me the error:

```
phpenv: no such command `shell'
```

**Comment by heitorsilva** [comment]
For some reason, what I needed to do was `source ~/.bash_profile`, and everything started working.

**Comment by madumlao** [comment]
Just FYI,
bash, by default, only loads the first of `~/.bash_profile` or `~/.profile`. If it sees `~/.bash_profile` it will ignore `~/.profile`.

In your case, `~/.bash_profile` should have been loaded by your shell by default on login. Changes to `~/.bash_profile` only take effect after logout and login.
