### ISSUE TITLE
Any plans merging this back into the original code base?

### ISSUE THREAD

**Issue by 99linesofcode** [madumlao/phpenv#17]
Title says it all actually 😄

**Comment by 99linesofcode** [comment]
Forget I said anything. Apparently the previous maintainer is not responding and the sole owner of the repository.. Hopefully we can avoid such a disaster in this repository ✌️

**Comment by madumlao** [comment]
@99linesofcode , it's been merged ;)

See phpenv/phpenv#57 :)
