### ISSUE TITLE
pyenv, nvm etc can't be access after installing phpenv

### ISSUE THREAD

**Issue by guangrei** [madumlao/phpenv#18]
hi i install phpenv by following instruction in `readme.md` everything is work well but my other command like pyenv, nvm cant be accessed except i run source ~/.bashrc

is possible to make phpenv run together with pyenv, nvm etc?

**Comment by madumlao** [comment]
Hi @guangrei,
Please redirect all issues now to https://github.com/phpenv/phpenv/issues. I will be closing this issue to redirect there.

If the advice below does not help you, please feel free to recreate the issue under phpenv/phpenv.

---

I am a regular user of pyenv, nenv, rbenv, (and a few others) and also contribute to some of them. To my knowledge there is no issue between phpenv/pyenv/rbenv/etc.

However, I DO know that rvm, nvm, etc are incompatible with rbenv, nenv, etc. It is possible that nvm is the one causing the incompatibilities, as the rvm family of language managers is very intrusive into shell functions and variables. Try removing nvm and replacing with [nenv](https://github.com/ryuone/nenv) and see if that helps.

Another possible cause of troubles is if you install the environment variables in `.profile` for one of them, but `.bash_profile` for the others. Bash will only `.bash_profile` if it exists, then `.profile` if it doesn't. Try to ensure that only one of those files exists. You may copy the file contents from one into the other.

**Comment by guangrei** [comment]
thanks, it's very helpful
