### ISSUE TITLE
Brew Install doesn't work

### ISSUE THREAD

**Issue by kadaan** [madumlao/phpenv#9]
In the meantime I have added a tap `kadaan/php` which installs phpenv correctly.  You can install the tap by running: `brew tap kadaan/php` and then install phpenv by running: `brew install kadaan/php/phpenv`.

**Comment by madumlao** [comment]
Hi @kadaan,
phpenv/phpenv has been revived as of #85 and all issues here will be migrated to https://github.com/phpenv/phpenv/issues.

Work on homebrew has begun in phpenv/phpenv#77 and I expect it to be ready within the week. I'll be closing this issue to be tracked there.
